### ISSUE TITLE
plmDCA error!

### ISSUE THREAD

**Issue by xiaohai90** [mskwark/genomeDCA#1] opened 2017-03-15 03:23 UTC
I'd like to use the genomeDCA to analyse my data, but when I move to the inference step: 02inference, there comes the errors with the plmDCA
command is as below:
python 00rungenomeDCA.py ../01sampling/sampled/sampling0000/input.seq

Error is like this:
Found!
 (NB: Please do set the path properly...)
Error using ^
MPOWER is not fully supported for integer classes. Both inputs must be scalar.
To compute elementwise POWER, use POWER (.^) instead.

Error in plmDCA_asymmetric (line 89)
    w=zeros(q+q^2*(N-1),N); %Matrix in which to store parameter estimates
    (column r will contain estimates from g_r).

Success
Bad file descriptor
Bad file descriptor
Bad file descriptor
Bad file descriptor
………………

And I think  it maybe the matlab version is not suitable. So could you please tell me which version of your matlab is ?

**Comment by mskwark** [comment] 2017-03-15 03:52
We have tested the code on MATLAB 2014b. We have also been running it successfully with earlier versions (e.g. 2012b) and Octave. Which MATLAB version do you use? Could you  send me the  ../01sampling/sampled/sampling0000/input.seq file?

**Comment by xiaohai90** [comment] 2017-03-15 04:23
Thanks for your immediately reply. 
Oops, I used MATLAB R2015b... Maybe that's the main question.
The file ../01sampling/sampled/sampling0000/input.seq, even the zip format, couldn't be uploaded successfully here, I'll send you from email later. 
PS: the input.seq file was generated based on the "M1_3442-postepidemic_strains_alignment.fasta", using the parameters as you described in your paper (Skwark MJ, 2017).

**Comment by xiaohai90** [comment] 2017-03-15 04:23
Thanks for your immediately reply. 
Oops, I used MATLAB R2015b... Maybe that's the main question.
The file ../01sampling/sampled/sampling0000/input.seq, even the zip format, couldn't be uploaded successfully here, I'll send you from email later. 
PS: the input.seq file was generated based on the "M1_3442-postepidemic_strains_alignment.fasta", using the parameters as you described in your paper (Skwark MJ, 2017).







在 2017-03-15 11:52:56，"Marcin Skwark" <notifications@github.com> 写道：


We have tested the code on MATLAB 2014b. We have also been running it successfully with earlier versions (e.g. 2012b) and Octave. Which MATLAB version do you use? Could you send me the ../01sampling/sampled/sampling0000/input.seq file?

**Comment by xiaohai90** [comment] 2017-03-16 06:04
Dear Marcin:
I've tried to do the 02inference step based on your data and parameters on MATLAB 2014b, but here comes the same error:


Error using ^
MPOWER is not fully supported for integer classes. Both inputs must be scalar.
To compute elementwise POWER, use POWER (.^) instead.


Error in plmDCA_asymmetric (line 89)
    w=zeros(q+q^2*(N-1),N); %Matrix in which to store parameter estimates
    (column r will contain estimates from g_r).


What should I do else? Could you please help me ? 






At 2017-03-15 11:52:56, "Marcin Skwark" <notifications@github.com> wrote:


We have tested the code on MATLAB 2014b. We have also been running it successfully with earlier versions (e.g. 2012b) and Octave. Which MATLAB version do you use? Could you send me the ../01sampling/sampled/sampling0000/input.seq file?

**Comment by mskwark** [comment] 2017-03-16 06:36
I will try to investigate this issue during the weekend. If you want to expedite the process, do send me your input data (or point me to a place I can download them from). The only thing I can say so far is that it works for me - but this is no consolation for you. 
To troubleshoot, I need to be able to reproduce your error. What platform are you running it on? Linux? Mac? Windows?

**Comment by xiaohai90** [comment] 2017-03-16 14:28
Thanks for your reply!
The attachments were the input files I used. I run the genomeDCA on Linux platform and the matlab is also a linux version (matlab_R2014b_linux). The parameters I used were all defult values, since I was trying to test whether the genomeDCA could work sucessfully on our linux platform. You could deal with these matters when you have time!
Thanks again~





At 2017-03-16 14:36:49, "Marcin Skwark" <notifications@github.com> wrote:


I will try to investigate this issue during the weekend. If you want to expedite the process, do send me your input data (or point me to a place I can download them from). The only thing I can say so far is that it works for me - but this is no consolation for you.
To troubleshoot, I need to be able to reproduce your error. What platform are you running it on? Linux? Mac? Windows?

**Comment by xiaohai90** [comment] 2017-03-21 07:27
Hi Marcin,
How are you doing?
Have you tried my input data on your genomeDCA? Does it work? I tried many times, changing the matlab version to 2014b and using python v2.7/v3.4,  but it still didn't work.
Hope to hearing from you soon!

**Comment by xiaohai90** [comment] 2017-03-23 09:05
Hi Marcin:

Since I didn't receive your replay for several days, I've been testing your code line by line all these days. Finally, I get some progress.


I found three little problems:
First: The errors occured in step 02inference was caused by wrong input.seq files rather than wrong matlab version.
      The first 6 lines in the sample0000/input.seq file produced by 00sample.py are as follow:
           
      There is a blank line between the sequence name and sequence, which is the real reason for the matlab error!
      Then, I read all your code, in line 75 of script 00datafiltering/00process.py, you didn't remove the "\n". And in the line 48 of script 01sampling/00sample.py, an extra "\n" was print into the input.seq.
      You may modify one of them.


Second: There may be two bugs in script 00datafiltering/00process.py.
      In line 14 to 33 of the script 00datafiltering/00process.py, the bases state of the last strain were not calculated to the frequencies. I think you should copy line 23-29 and and them after the line 33. And line 75-97 has the same situation.


Third: This problem is about line 23-28 of the script 01sampling/00sample.py. 
          I'm not sure about this problem, so I just wonder if there should be added a code "chunks.append(chunk)" after line 28 (the ending of the for loop), to append the last chunk to chunks.


Last but not the least, I found that in the file input.mapping, there are some duplicate values in column 2. According to my understanding, this column means the positions on genome. And they will be calculated correlation bwtween each other. Did this affect the results?
Additionly, in your paper, para 2 page 16, 3,442 genomes of the S. pyogenes results in 324 SNPs. I download your alignment file, using the same parameters, and I got 323 SNPs in total. Could you please explain me for all above?


 
Hope to hearing from you !
Xiaohai

At 2017-03-16 14:36:49, "Marcin Skwark" <notifications@github.com> wrote:


I will try to investigate this issue during the weekend. If you want to expedite the process, do send me your input data (or point me to a place I can download them from). The only thing I can say so far is that it works for me - but this is no consolation for you.
To troubleshoot, I need to be able to reproduce your error. What platform are you running it on? Linux? Mac? Windows?

**Comment by mskwark** [comment] 2017-03-27 20:19
Xiaohai,
Thank you for your pointers. You were right, that there were a few slips in the GitHub version of the code. They are now fixed. Let me assure you, that the results in the paper have been obtained with a version of code, which worked as described in the paper.
The (indubitably) buggy sampling - which has been fixed now as well - should not affect the results (but affects slightly computational performance) in any meaningful way.
I did appreciate your comments and pointers and I do apologize for a delay in response.
Cheers,
Marcin

**Closed as completed by mskwark** 2017-03-27 20:19 UTC

**Comment by xiaohai90** [comment] 2017-03-28 07:09
Hi Marcin:


Thanks for your kindly help and feedback. 
You said that the code had been fixed. Have you upgraded the GitHub version or uploaded it somewhere else? I can't find it. Could you please tell me where I can get it?
Thanks again!


Xiaohai

**Comment by mskwark** [comment] 2017-03-28 11:51
Hi Xiaohai,
It should be in GitHub repository now...

**Comment by xiaohai90** [comment] 2017-03-31 00:37
I got it. Thanks for your help sincerely!






At 2017-03-28 19:51:46, "Marcin Skwark" <notifications@github.com> wrote:


Hi Xiaohai,
It should be in GitHub repository now...

**Comment by xiaohai90** [comment] 2017-03-31 08:06
Hi Marcin:
I'm very sory to bother you again...
Two question about script 03postprocessing/01summary.py:
1. In line 6 of the script, it reads "def makesummary(directories, outfile):", which means that you defined a function named makesummary. But at line 69, you called it :makesummaries(indirs, outfile). I think the function name in line69 should be same with that in line 6, am I right?
2. Should I run the script in directory 03postprocessing/? or 01.sampling/sampled/ ? As you discribed In line24 of 03postprocessing/README.md: "To compute summary statistics, run `./01summary.py outfile.txt sampled/sampling*/` ", I run it in 03postprocessing/, but it didn.t work. Then I run it in 01.sampling/sampled/, it worked. I think the path "sampled/sampling*/" in command line is useless and the main reason maybe is in line12 of script 03postprocessing/01summary.py. 


Could you please help me with these two questions?
Hoping your help!


Xiaohai










At 2017-03-28 19:51:46, "Marcin Skwark" <notifications@github.com> wrote:


Hi Xiaohai,
It should be in GitHub repository now...

**Comment by xiaohai90** [comment] 2017-04-07 05:38
Hi Marcin:


Have you ever received my last message? I got troubles when doing the step of 03.postprocessing... I need your help!


Could you please help me with those two questions?
Hoping your help!


Xiaohai

**Comment by mskwark** [comment] 2017-04-10 14:24
Hi,
I am ever so sorry that I have yet to respond to your emails. I have
overlooked the previous one completely. I will try to get back to you later
today.
Cheers,
Marcin

**Comment by mskwark** [comment] 2017-04-11 15:59
Hi Xiaohai,

Thank you for your email, as it allowed me to clear a few slips in the code.
The script should be run wherever you please. If your runs are in
/home/xiaohai/genomeDCA/sampled/sampling* then you need to run
./01summary.pl myOutputFile.txt /home/xiaohai/genomeDCA/sampled/sampling*
or a corresponding relative path.
Cheers,
Marcin

**Comment by xiaohai90** [comment] 2017-04-12 01:22
Hi Marcin，
Thanks very much for your kindly help! It does work successfully now! Hooray!


Additionally, I still have three small but a little bit urgent questions needing your help!
1. In line7 of script 03postprocessing/00process.py, it reads "excludeThreshold = 10000". Does this mean that if the real distance between two sites in the coupling are less than 10000bp, this coupling pairs will be excluded? If so,then why do you choose 10000 to be the cutoff value?


2. In line51-54 of script 03postprocessing/00process.py, I think the function of these codes is to print the first 3000 coupling sites of each input. And I just wonder why choose 3000?


3. In your article, Fig1A was a Gumbel distribution fitted on the sample, and you said the vertical axis corresponds to the log10 probability of a coupling coefficient exceeding the value of the curve on the horizontal axis. How do you calculate the probability?


Hoping for your reply!


Best Regards!
Xiaohai



At 2017-04-11 23:59:23, "Marcin Skwark" <notifications@github.com> wrote:
Hi Xiaohai,

Thank you for your email, as it allowed me to clear a few slips in the code.
The script should be run wherever you please. If your runs are in
/home/xiaohai/genomeDCA/sampled/sampling* then you need to run
./01summary.pl myOutputFile.txt /home/xiaohai/genomeDCA/sampled/sampling*
or a corresponding relative path.
Cheers,
Marcin
